from langchain_community.llms import Ollama
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
import os
import sys
import subprocess
from datetime import datetime


def print_banner():
    """Display tool branding."""
    print("\n" + "=" * 70)
    print("🛡️  AI SECURITY LOG ANALYZER")
    print("=" * 70)
    print("Built by: Cicada (Shaheer Hussain)")
    print("GitHub:   @shaheersec | linktr.ee/shaheersec")
    print("Powered:  Ollama + Llama 3.1 8B (100% Local & Free)")
    print("=" * 70)


def clean_output(text):
    """Remove markdown formatting for clean terminal display."""
    text = text.replace('**', '')
    text = text.replace('*', '')
    return text


def convert_etl_to_text(etl_file):
    """Convert Windows ETL (Event Trace Log) file to readable text format."""
    print(f"\n🔄 Detected ETL file - converting to text format...")
    
    # Create temporary text file path
    temp_txt_file = etl_file.replace('.etl', '_converted.txt')
    
    try:
        # Use Windows tracerpt utility to convert ETL to text
        command = f'tracerpt "{etl_file}" -o "{temp_txt_file}" -of CSV -summary "{temp_txt_file}.summary"'
        
        print(f"⏳ Converting... (this may take 10-30 seconds)")
        
        result = subprocess.run(
            command,
            shell=True,
            capture_output=True,
            text=True,
            timeout=60
        )
        
        if result.returncode == 0 and os.path.exists(temp_txt_file):
            print(f"✅ Conversion successful!")
            print(f"📄 Converted file: {temp_txt_file}")
            return temp_txt_file
        else:
            print(f"❌ Conversion failed: {result.stderr}")
            return None
            
    except subprocess.TimeoutExpired:
        print("❌ Conversion timed out (file too large)")
        return None
    except Exception as e:
        print(f"❌ Conversion error: {str(e)}")
        return None


def save_report(log_file, analysis, output_dir="reports"):
    """Save analysis to a formatted report file."""
    
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"security_report_{timestamp}.txt"
    filepath = os.path.join(output_dir, filename)
    
    report = f"""
{'=' * 70}
SECURITY LOG ANALYSIS REPORT
{'=' * 70}

Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Analyzed File: {log_file}
Tool: AI Security Log Analyzer (Ollama + Llama 3.1 8B)

{'=' * 70}

{analysis}

{'=' * 70}
Report generated by Cicada (@shaheersec)
https://linktr.ee/shaheersec
{'=' * 70}
"""
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(report)
    
    return filepath


class SecurityLogAnalyzer:
    """AI-powered security log analyzer using Ollama + Llama 3.1."""
    
    def __init__(self, model="llama3.1:8b"):
        print(f"\n🤖 Initializing AI Log Analyzer with {model}...")
        
        self.llm = Ollama(model=model, temperature=0)
        
        self.prompt = PromptTemplate(
            input_variables=["logs"],
            template="""You are a cybersecurity expert analyzing server logs.

Analyze these logs and provide a clear security report:

LOGS:
{logs}

Write your analysis in PLAIN TEXT ONLY (no markdown, no asterisks, no special formatting).

Use this structure:

THREAT LEVEL: [Critical / High / Medium / Low]

EXECUTIVE SUMMARY:
[One clear sentence explaining what happened]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SECURITY ISSUES DETECTED:

1. [Attack Type]
   IP Address: [source IP]
   What happened: [simple explanation]
   Risk: [why this matters]

2. [Next attack]
   IP Address: [source IP]
   What happened: [simple explanation]
   Risk: [why this matters]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

IMMEDIATE ACTIONS REQUIRED:

1. [First action - be specific]
2. [Second action - be specific]
3. [Third action - be specific]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Remember: Use plain text only, no markdown formatting."""
        )
        
        self.chain = LLMChain(llm=self.llm, prompt=self.prompt)
        print("✅ Analyzer ready!\n")
    
    def analyze_file(self, file_path):
        """Run AI analysis on a log file."""
        
        # Check if file is ETL format and convert if needed
        original_file = file_path
        is_etl = file_path.lower().endswith('.etl')
        
        if is_etl:
            converted_file = convert_etl_to_text(file_path)
            if converted_file is None:
                print("\n❌ Could not convert ETL file. Exiting.")
                return None
            file_path = converted_file
        
        print(f"\n📂 Reading log file: {file_path}")
        
        try:
            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                logs = f.read()
            
            num_lines = len(logs.splitlines())
            print(f"✅ Loaded {num_lines} log entries")
            
            if num_lines == 0:
                print("⚠️  Warning: Log file is empty!")
                
                # Clean up temporary converted file
                if is_etl and os.path.exists(file_path):
                    os.remove(file_path)
                    summary_file = file_path + ".summary"
                    if os.path.exists(summary_file):
                        os.remove(summary_file)
                
                return None
            
        except FileNotFoundError:
            print(f"❌ Error: File '{original_file}' not found.")
            return None
        except PermissionError:
            print(f"❌ Error: Permission denied to read '{original_file}'")
            return None
        except Exception as e:
            print(f"❌ Error reading file: {str(e)}")
            return None
        
        print("\n🔍 Running AI security analysis...")
        print("⏳ This may take 10-30 seconds...\n")
        
        try:
            result = self.chain.invoke({"logs": logs})
            
            if hasattr(result, 'text'):
                analysis = result.text
            elif isinstance(result, dict) and 'text' in result:
                analysis = result['text']
            else:
                analysis = str(result)
            
            clean_analysis = clean_output(analysis)
            
            # Add emoji indicators for threat level
            if 'THREAT LEVEL: Critical' in clean_analysis:
                clean_analysis = clean_analysis.replace('THREAT LEVEL: Critical', '🔴 THREAT LEVEL: Critical 🔴')
            elif 'THREAT LEVEL: High' in clean_analysis:
                clean_analysis = clean_analysis.replace('THREAT LEVEL: High', '🟠 THREAT LEVEL: High 🟠')
            elif 'THREAT LEVEL: Medium' in clean_analysis:
                clean_analysis = clean_analysis.replace('THREAT LEVEL: Medium', '🟡 THREAT LEVEL: Medium 🟡')
            elif 'THREAT LEVEL: Low' in clean_analysis:
                clean_analysis = clean_analysis.replace('THREAT LEVEL: Low', '🟢 THREAT LEVEL: Low 🟢')
            
            print("=" * 70)
            print(clean_analysis)
            print("=" * 70)
            
            # Save report using original filename
            report_path = save_report(original_file, clean_analysis)
            
            print(f"\n📄 Detailed report saved to: {report_path}")
            print("💡 Open this file to view the full analysis")
            
            # Clean up temporary converted file
            if is_etl and os.path.exists(file_path):
                print(f"\n🗑️  Cleaning up temporary converted file...")
                try:
                    os.remove(file_path)
                    summary_file = file_path + ".summary"
                    if os.path.exists(summary_file):
                        os.remove(summary_file)
                except:
                    pass
            
            return analysis
            
        except Exception as e:
            print(f"❌ Analysis error: {str(e)}")
            print("\n💡 Tip: Make sure Ollama is running and Llama 3.1 is installed")
            print("   Run: ollama pull llama3.1:8b")
            
            # Clean up on error
            if is_etl and os.path.exists(file_path):
                try:
                    os.remove(file_path)
                    summary_file = file_path + ".summary"
                    if os.path.exists(summary_file):
                        os.remove(summary_file)
                except:
                    pass
            
            return None


def get_log_file_path():
    """Prompt user for log file path or use sample."""
    default_sample = "logs/sample_apache.log"
    
    print("\n" + "=" * 70)
    print("📁 LOG FILE SELECTION")
    print("=" * 70)
    print(f"\nDefault sample: {default_sample}")
    print("\nOptions:")
    print("  1. Press ENTER to use sample log (demo)")
    print("  2. Type/paste your log file path")
    print("  3. Drag & drop a file into this window")
    print("\n💡 Supports: .log, .txt, .etl (auto-converts ETL files)\n")
    
    user_input = input("Enter log file path (or press Enter for sample): ").strip()
    user_input = user_input.strip('"').strip("'")
    
    if user_input == "":
        if os.path.exists(default_sample):
            print(f"\n✅ Using sample log: {default_sample}")
            return default_sample
        else:
            print(f"\n⚠️  Sample log not found: {default_sample}")
            return None
    else:
        if os.path.exists(user_input):
            print(f"\n✅ Using log file: {user_input}")
            return user_input
        else:
            print(f"\n❌ File not found: {user_input}")
            return None


def main():
    print_banner()
    
    if len(sys.argv) > 1:
        log_file = sys.argv[1]
        print(f"\n📂 Command-line argument detected: {log_file}")
    else:
        log_file = get_log_file_path()
    
    if log_file is None:
        print("\n❌ No valid log file provided. Exiting.")
        return
    
    analyzer = SecurityLogAnalyzer()
    analyzer.analyze_file(log_file)
    
    print("\n" + "=" * 70)
    print("✅ Analysis complete!")
    print("=" * 70)
    print("\n💡 To analyze another file:")
    print("   python log_analyzer.py <path-to-log-file>")
    print("\n🔗 Cicada (@shaheersec) | linktr.ee/shaheersec")
    print("=" * 70)
    print()


if __name__ == "__main__":
    main()